### ISSUE TITLE
Inspect what `/accepteula` parameter set

### ISSUE THREAD

**Issue by Ash258** [shovel-org/Windows-Sysinternals-Bucket#4]
Execution with accepteula could be runed only once. Other executions do no need it. No need to provide it on each execution (at least on single instance of powershell / system)

Find some file, registry, whatever they set.

Test if single execution with accepteula will be kept after shell / system restart. (best in docker)

**Comment by rasa** [comment]
https://peter.hahndorf.eu/blog/post/2010/03/07/WorkAroundSysinternalsLicensePopups says one reg entry avoids having to include `/accepteula`, but wouldn’t we want to include it every time, as not everyone can/wants to write to their registry?

**Comment by Ash258** [comment]
> not everyone can write to their registry

It is Current User hive. Everyone can edit these registry keys without elevation.

![A](https://i.imgur.com/Z1aY8on.png)

> not everyone wants to write to their registry

This values will be written on first startup all the time. I do not see problem with adding it manually. 

Main reason is manifest ergonomics. It is much more cleaner to add `post_install` block with `New-ItemProperty HKCU:\Software\Sysinternals\$ManifestName -Name EulaAccepted -Value 1 -Type DWord -Force | Out-Null` instead of multiple bins / shortcuts with 3 values.
